# Here CURDIR is assumed to be the root folder of the project.

CHRACACTERGO_ROOT_FOLDER=${CURDIR}
CHRACACTERGO_BUILD_FOLDER=${CURDIR}/Build
CHRACACTERGO_UTIL_FOLDER=${CURDIR}/Util
CHRACACTERGO_BUILD_TOOLS_FOLDER=${CHRACACTERGO_UTIL_FOLDER}/BuildTools

CHRACACTERGOUE5_ROOT_FOLDER=${CURDIR}/CharacterGoUnreal
CHRACACTERGOUE5_PLUGIN_ROOT_FOLDER=${CURDIR}/CharacterGoUnreal/Plugins/CharacterGO
CHRACACTERGO_PYTHONAPI_ROOT_FOLDER=${CURDIR}/PythonAPI
CHRACACTERGO_PYTHONAPI_SOURCE_FOLDER=${CHRACACTERGO_PYTHONAPI_ROOT_FOLDER}/CharacterGO
CHRACACTERGOUE5_PLUGIN_ROOT_FOLDER=${CURDIR}/CharacterGoUnreal/Plugins/CharacterGO



# LibCharacterGo